url: https://y7kim.github.io #https://shanwiich.github.io #https://uhcougarettes.com/ #https://y7kim.github.io
baseurl: #/uhcougarettes #/agency-jekyll-theme/

# Site settings
title: Cougarettes
email: your-email@domain.com
description: "Welcome to UH Cougarettes! Our organization strives to build a sense of camaraderie amongst women in STEM."

# Team names, titles and social links
people:

- name: Andrea Davila Figueroa
  pic: andrea
  position: President
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/andrea-davila-figueroa/
  #  - title: facebook
   #   url: #
   # - title: stack-overflow
   #   url: #

- name: Khadeeja Tapkirwala
  pic: khadeeja
  position: Vice President
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/khadeeja-tapkirwala-a40878278/
 #   - title: facebook
 #     url: #
 #   - title: stack-overflow
 #     url: #

- name: Farzana Hajee
  pic: farzana
  position: Treasurer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/farzanahajee/
 #   - title: facebook
 #     url: #
 #   - title: stack-overflow
 #     url: #

- name: Keertana Putam
  pic: keertana
  position: Secretary
  social:
    - title: linkedin
      url: https://linkedin.com/in/keertana-putam-9294812b1
 #   - title: facebook
 #     url: #
 #   - title: stack-overflow
 #     url: #

- name: Sara Montes
  pic: sara
  position: Recruitment Chair
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/sara-montes-cs77
 #   - title: facebook
 #     url: #
 #   - title: stack-overflow
 #     url: #

- name: Nawal Kashif
  pic: nawal
  position: TR Program Manager
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/nawal-kashif-90149737b/
  #   - title: facebook
  #     url: #
  #   - title: stack-overflow
  #     url: #

- name: Safa Ansari
  pic: safa
  position: TR Program Manager
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/safa-a-868620374/
  #   - title: facebook
  #     url: #
  #   - title: stack-overflow
  #     url: #

- name: Aliza Salman
  pic: aliza (2)
  position: Events Coordinator
  social:
    - title: linkedin
      url: http://linkedin.com/in/aliza-salman-538573269
 #   - title: facebook
 #     url: #
 #   - title: stack-overflow
 #     url: #

- name: Stephanie Anongdeth
  pic: stephanie
  position: Outreach Chair
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/stephanie-anongdeth/
  #   - title: facebook
  #     url: #
  #   - title: stack-overflow
  #     url: #

- name: Ashley Nguyen
  pic: ashley
  position: Webmaster
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ashleynguyencs/
 #   - title: facebook
 #     url: #
 #   - title: stack-overflow
 #     url: #

#- name: temp
#  pic: temp
#  position: Technical lead
#  social:
#    - title: linkedin
#      url: https://www.linkedin.com/in/charity-smith-748b24232/
  #  - title: facebook
  #    url: #
  #  - title: google-plus
   #   url: #

- name: Isabel Lara
  pic: isabel
  position: Digital Marketer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/bellalara/
 #   - title: facebook
 #     url: #
 #   - title: stack-overflow
 #     url: #

- name: Arpitha Ashokan
  pic: arpitha
  position: Marketing Chair
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/arpithaashokan2025/
  #  - title: facebook
  #    url: #
  #  - title: google-plus
   #   url: #

- name: Elle Herrera
  pic: elle
  position: Coding Event Coordinator
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/darelle-herrera
  #  - title: facebook
  #    url: #
  #  - title: google-plus
   #   url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/uhcougarettes/?igshid=qge4kwdiiptk
    icon: fab
  - title: discord
    url: https://discord.com/invite/cFRjD3B
    icon: fab
  - title: comments
    url: https://groupme.com/join_group/60979871/R7xE8exb
    icon: fas
  # - title: discord
  #   url: https://discord.gg/W92MukBS
 # - title: bitbucket 
  #  url: http://bitbucket.org/jekyll
#  - title: github
  #  url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-hacker
